Feature/#7 add custom file
traP-jp/traO-Judge-judge pull request #59
Opened 2024-10-05 02:01 UTC by hayatroid

## 関連Issue

- close #7

## 概要

ファイルを管理する構造体を実装しました。下記のような使い方を想定しています。

- `FileFactory::new()` に基準となるパスを渡す。ファイル / ディレクトリ / ハードリンクはこのパス直下に作られる。
- `FileFactory::create_file()` でファイル / ディレクトリを作成する。
- `FileFactory::create_hardlink_of()` でファイルのハードリンクを作成する。
- ファイル / ディレクトリがドロップすると、これは削除される。

```rust
#[cfg(test)]
mod tests {
    use std::{path::PathBuf, thread::sleep, time::Duration};

    use anyhow::Result;
    use uuid::Uuid;

    use crate::custom_file::{
        directory::Directory, file_factory::FileFactory, text_file::TextFile,
        traits::FileFactory as _,
    };

    #[test]
    fn test() -> Result<()> {
        let path = PathBuf::from(".");
        let ff = FileFactory::new(path.clone())?;
        {
            // "./{uuid}" ディレクトリを作成
            let uuid = Uuid::new_v4();
            let dir = ff.create_file::<Directory>(uuid, ())?;

            let path2 = path.join(uuid.to_string());
            let ff2 = FileFactory::new(path2)?;
            {
                // "./{uuid}/{uuid2}" ファイルを作成，"hogehoge" と書き込み
                let uuid2 = Uuid::new_v4();
                let contents = "hoge".to_string();
                let file = ff2.create_file::<TextFile>(uuid2, Some(contents))?;
                {
                    // "./{uuid}/{uuid3}" に "./{uuid}/{uuid2}" のハードリンクを作成
                    let uuid3 = Uuid::new_v4();
                    let hardlink = ff2.create_hardlink_of::<TextFile>(uuid3, &file)?;
                    sleep(Duration::from_secs(5));
                    // hardlink がドロップ，"./{uuid}/{uuid3}" ファイルを削除
                }
                sleep(Duration::from_secs(5));
                // file がドロップ，"./{uuid}/{uuid2}" ファイルを削除
            }
            sleep(Duration::from_secs(5));
            // dir がドロップ，"./{uuid}" ディレクトリを削除
        }
        Ok(())
    }
}
```

## チェックリスト
- [ ] テストが通っている
- [ ] 下記のいずれかを満たしている
    - - [ ] 変更点についてテストを追加/修正した
    - - [ ] テストを追加するissueを立てた
    - - [ ] テストが不要な変更である
- [ ] レビュワーを指定した
- [ ] タグをつけた

## 補足

2024-10-05 02:13 UTC, hayatroid commented
チェックリストのテストについてはどうするのがよいですか

2024-10-05 08:13 UTC, comavius commented on judge-control-app/src/custom_file/directory.rs
> +        Err(anyhow!("hard link not allowed for directory"))
これ知りませんでしたごめんなさい
シンボリックリンクで同じような振る舞いを再現してほしいです

2024-10-05 08:14 UTC, comavius commented on judge-control-app/src/custom_file/directory.rs
> +            eprintln!("{:?}", e);
grafanaについて調べてから実装したいので、この部分を!unimplementedに変更してほしいです

2024-10-05 08:17 UTC, comavius commented on judge-control-app/src/custom_file/text_file.rs
> +    fn read(&self) -> Result<String> {
readがdead codeになる気がします

2024-10-05 08:19 UTC, comavius requested changes
設計に色々不備があってごめん

2024-10-05 08:38 UTC, hayatroid commented on judge-control-app/src/custom_file/text_file.rs
> +    fn read(&self) -> Result<String> {
@comavius どう対処すればよいですか？`#[allow(dead_code)]` でよいですか？

2024-10-05 10:37 UTC, comavius commented
> チェックリストのテストについてはどうするのがよいですか

今回はなしでissueだけお願いします

2024-10-05 10:38 UTC, comavius commented on judge-control-app/src/custom_file/text_file.rs
> +    fn read(&self) -> Result<String> {
クラス内部で呼び出さないならいらない気がします

2024-10-20 08:06 UTC, hayatroid commented
@comavius レビューお願いします．`directory.rs` と `text_file.rs` にある 4 箇所の `unimplemented!`（ファイル削除時のエラーハンドリングをどうするかの部分）を消して，下記のようなプログラムを書くとテストすることができると思います．

シンボリックリンクを発行する機能を `Entity` に実装していないので，

- `Entity` は `Arc<RwLock<>>` でラップして使う．
- `Entity` のシンボリックリンクは `FileFactory::create_file()` で作成する
- `Link` のシンボリックリンクは `FileFactory::create_symlink_of()` で作成する

とする必要があります．これまでに指摘された点はすべて修正したつもりですが，反映忘れ等あったらすみません．

```rust
#[cfg(test)]
mod tests {
    use std::{
        path::PathBuf,
        sync::{Arc, RwLock},
        thread::sleep,
        time::Duration,
    };

    use uuid::Uuid;

    use crate::custom_file::{
        directory::{DirectoryEntity, DirectoryLink},
        file_factory::FileFactory,
        text_file::{TextFileEntity, TextFileLink},
        traits::FileFactory as _,
    };

    fn create_entity() -> anyhow::Result<(
        FileFactory,
        Arc<RwLock<DirectoryEntity>>,
        Arc<RwLock<TextFileEntity>>,
    )> {
        let ff = FileFactory::new(PathBuf::from("."))?;
        let dir_entity = ff.create_file::<DirectoryEntity>(Uuid::new_v4(), ())?;
        let txt_entity = ff.create_file::<TextFileEntity>(Uuid::new_v4(), "hoge".to_string())?;
        Ok((ff, Arc::new(RwLock::new(dir_entity)), Arc::new(RwLock::new(txt_entity))))
    }

    fn create_symlink_of_entity() -> anyhow::Result<(FileFactory, DirectoryLink, TextFileLink)> {
        let (ff, dir_entity, txt_entity) = create_entity()?;
        let dir_symlink = ff.create_file::<DirectoryLink>(Uuid::new_v4(), dir_entity.clone())?;
        let txt_symlink = ff.create_file::<TextFileLink>(Uuid::new_v4(), txt_entity.clone())?;
        Ok((ff, dir_symlink, txt_symlink))
    }

    fn create_symlink_of_symlink() -> anyhow::Result<(FileFactory, DirectoryLink, TextFileLink)> {
        let (ff, dir_symlink, txt_symlink) = create_symlink_of_entity()?;
        let dir_symlink2 = ff.create_symlink_of(Uuid::new_v4(), &dir_symlink)?;
        let txt_symlink2 = ff.create_symlink_of(Uuid::new_v4(), &txt_symlink)?;
        Ok((ff, dir_symlink2, txt_symlink2))
    }

    #[test]
    fn test_create_entity() -> anyhow::Result<()> {
        // "." 以下に dir_entity, txt_entity が作られる．
        // dir_entity, txt_entity が 5 秒後に消える．
        let (_, dir_entity, txt_entity) = create_entity()?;
        sleep(Duration::from_secs(5));
        drop(dir_entity);
        drop(txt_entity);
        Ok(())
    }

    #[test]
    fn test_create_symlink_of_entity() -> anyhow::Result<()> {
        // "." 以下に dir_entity, txt_entity が作られる．
        // "." 以下に dir_symlink, txt_symlink が作られる．
        // dir_symlink, txt_symlink が 5 秒後に消える．
        // dir_entity, txt_entity が 5 秒後に消える．
        let (_, dir_symlink, txt_symlink) = create_symlink_of_entity()?;
        sleep(Duration::from_secs(5));
        drop(dir_symlink);
        drop(txt_symlink);
        Ok(())
    }

    #[test]
    fn test_create_symlink_of_symlink() -> anyhow::Result<()> {
        // "." 以下に dir_entity, txt_entity が作られる．
        // "." 以下に dir_symlink, txt_symlink が作られる．
        // "." 以下に dir_symlink2, txt_symlink2 が作られる．
        // dir_symlink, txt_symlink が即消える．
        // dir_symlink2, txt_symlink2 が 5 秒後に消える．
        // dir_entity, txt_entity が 5 秒後に消える．
        let (_, dir_symlink2, txt_symlink2) = create_symlink_of_symlink()?;
        sleep(Duration::from_secs(5));
        drop(dir_symlink2);
        drop(txt_symlink2);
        Ok(())
    }
}
```

2024-10-24 13:57 UTC, comavius approved these changes
LGTM、言っていることが二転三転してごめん、ありがとう

2024-10-25 02:47 UTC, merged